$(document).on 'turbolinks:load', ->
  $('a.js-scroll-trigger[href*="#"]:not([href="#"])').click ->
    if location.pathname.replace(/^\//, '') == @pathname.replace(/^\//, '') and location.hostname == @hostname
      target = $(@hash)
      target = if target.length then target else $('[name=' + @hash.slice(1) + ']')
      if target.length
        $('html, body').animate { scrollTop: target.offset().top - 54 }, 1000, 'easeInOutExpo'
        return false
    return

  $('.js-scroll-trigger').click ->
    $('.navbar-collapse').collapse 'hide'
    return

  $('body').scrollspy
    target: '#mainNav'
    offset: 56

  navbarCollapse = ->
    if $('#mainNav').offset().top > 100
      $('#mainNav').addClass 'navbar-shrink'
    else
      $('#mainNav').removeClass 'navbar-shrink'
    return


  navbarCollapse()

  $(window).scroll navbarCollapse
  
  return

  # ---
  # generated by js2coffee 2.2.0